config/routes.rb
Rails.application.routes.draw do
  # LISTS
  root "lists#index"
  get "/lists", to: "lists#index" # Just redirect to the root path

  get "/lists/new", to: "lists#new", as: :new_list
  get "/lists/:id", to: "lists#show", as: :list
  post "/lists", to: "lists#create"

  get "/lists/:id/bookmarks/new", to: "bookmarks#new", as: :bookmarks
  post "/lists/:id/bookmarks", to: "bookmarks#create", as: :list_bookmarks
  delete "/bookmark/:id", to: "bookmarks#destroy", as: :delete_bookmark
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, presence: true
  validates :list, presence: true
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :image
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true
  validates :name, presence: :true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true
  validates :title, presence: :true

  validates :overview, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.destroy
      redirect_to list_path(@bookmark.list), status: :see_other
    else
      redirect_to list_path(@bookmark.list), status: 500
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show]

  def to_root
    redirect_to root_path
  end

  def index
    @lists = List.all
  end

  def show
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="page-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<h1 style="margin-bottom: 0px;">Lists</h1>

<%= link_to "Create a list", new_list_path, class: "create-list" %>

<div class="lists">
  <% @lists.each do |list| %>
    <%= link_to list_path(list) do %>
      <div class="list-wrapper" style="height: 200px; background-image: url('<%= list.image.key ? cl_image_path(list.image.key, height: 200, crop: :fill) : "" %>');">
        <h2 class="list-link"><%= list.name %></h2>
      </div>
    <% end %>
  <% end %>
</div>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :image, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<div class="banner" style="background-image: url('<%= @list.image.key ? cl_image_path(@list.image.key) : "" %>');">
  <h1>List: <%= @list.name %></h1>
</div>

<%= link_to "New bookmark", bookmarks_path, class: "new-link" %>

<div class="cards">
  <% @bookmarks.each do |bookmark| %>
    <div class="card">
      <h2 class="movie-title"><%= bookmark.movie.title %></h2>
      <p class="comment"><%= bookmark.comment %></p>
      <%= link_to "Delete", delete_bookmark_path(bookmark), data: {turbo_method: :delete}%>
    </div>
  <% end %>
</div>

<%= link_to "All lists", root_path, class: "all-link" %>